src/nodes/image.js

I replaced the pin from input to output. worked fine for me.

FadeImage node didn't have output pin

---

src/nodes/interface.js

The HSliderWidget node used an onInit() callback which does not exist instead of onAdded().

Fix HSlider widget not initializing correctly

---

build/litegraph.js
build/litegraph.min.js
src/litegraph.js

isValidConnection was not working.

Fix wrong indexing in isValidConnection

---

build/litegraph.js
src/litegraph.js

Add option to hide border around initial canvas
Add an option to prevent zoom influence on cavas alpha
fix typo
update build
add param to change title color
Fix ctrl-z

Hide border and other changes

---

README.md

This pull requests adds instructions on how to launch the demo on your local computer. As a newcomer to the project, it can be hard to track down exactly how to open the demo, especially not knowing that it is not enough to open `demo/index.html`, but you have to start the server.
Thank you for a cool project!

Add Demo section to README

---

src/litegraph.js

Added various options and methods I needed for a project myself.

Various stuff

---

src/litegraph.js

Added arrow shape for input/output

Arrow shape

---

build/litegraph.js
build/litegraph.min.js
css/litegraph.css
src/litegraph.js

* Added callbacks to allow for more specific customization of node titles: 
```
onDrawTitleBar(ctx, title_height, size, scale, fgcolor)
onDrawTitleBox(ctx, title_height, size, scale)
onDrawTitleText(ctx, title_height, size, scale, title_text_font, selected)
```
* Fixed the missing "Tahoma" font for context-menus

Callbacks & fixes

---

.gitignore
src/litegraph.js

correct typos
fix [onDrawCollapsed never get called](https://github.com/jagenjo/litegraph.js/blob/59035cf2460a737bca146a51efd5521c1adbfd64/src/litegraph.js#L5908)

fix: correct typo

---

build/litegraph.js
build/litegraph.min.js
src/litegraph.js

`mousemove` event should not trigger callback of button widget

fix(widget): unexpected button callback call

---

build/litegraph.js
build/litegraph.min.js
src/litegraph.js

`this.addOutput('default', 'node', { locked: true, nameLocked: true });` will not make name locked like below:

fix(slot): `nameLocked` option not work

---

.gitignore
.prettierrc
.vscode/extensions.json
css/litegraph-editor.css
css/litegraph.css
package.json
src/litegraph-editor.js
src/litegraph.js
src/nodes/audio.js
src/nodes/base.js
src/nodes/events.js
src/nodes/glfx.js
src/nodes/gltextures.js
src/nodes/graphics.js
src/nodes/input.js
src/nodes/interface.js
src/nodes/logic.js
src/nodes/math.js
src/nodes/math3d.js
src/nodes/midi.js
src/nodes/network.js
src/nodes/strings.js

added `npm run prettier` command
and formatted existed code

Configure prettier

---

package.json
src/litegraph.d.ts

feat: support typescript

---

src/litegraph.js

It can fix contextmenu position issue in MS Edge.

Support Microsoft Edge browser

---

src/litegraph.d.ts
src/litegraph.js

see https://github.com/jagenjo/litegraph.js/issues/122
I think it's not more than these few lines

Added hook for slot context menu

---

src/litegraph.d.ts

fixes typedef for onDrawBackground and onDrawForeground

---

src/litegraph.js

Getting continuous errors in a loop, because of this error. It says catch_errors of undefined

fixed this pointer in the code

---

src/litegraph.js

Extracted function to draw slot graphics and modified shape selection to allow custom action/event slot shape

Extracted function to draw slot graphics and modified shape selection

---

guides/README.md

I had a bit of a hard time tracking down how to do this, so thought it would be worth adding to the documentation.

Add documentation on customising link tooltips

---

build/litegraph.js
build/litegraph.min.js

I forgot to build the changes from pull request #176 (woops). This PR includes a build that has the latest changes.

Build changes from PR #176

---

src/litegraph.d.ts
src/litegraph.js

Recovering lost changes from pull request [#154](https://github.com/jagenjo/litegraph.js/pull/154) after [this commit](https://github.com/jagenjo/litegraph.js/commit/c74d8760b11dddfc46c17b569cbca1d46eebdb5a#diff-1655684d99f5f20239a900b1017bb50cL3645)

Remade lost changes from pull request #154

---

src/litegraph.js

Hi @jagenjo,
In our project we had a requirement for multi-level folders under the "add node" context menu.  We wanted to share this with you if this is something you'd like to have.  JavaScript is not my primary language so if anyone wishes to refactor then please feel free to comment or make changes!
Thank you Jagenjo for a fantastic bit of code.

multi-level context menus

---

src/litegraph.d.ts

Add TS support on LGraphNode.has_errors property.

TS support about LGraphNode.has_errors

---

src/litegraph.d.ts

Add TS support to LGraphNode.onPropertyChanged.

TS support about LGraphNode.onPropertyChanged

---

src/litegraph.d.ts

TS support about LGraphNode.disconnectOutput

---

src/nodes/events.js
src/nodes/math.js

Again, maybe I'm plain wrong but it doesn't convert a lot without an output right?
BTW, this.addInput("in", "*"); doesn't work for numbers for me, but this.addInput("in", ""); does.

an output for converter?

---

src/nodes/math.js

updated converter input

---

css/litegraph.css
editor/js/demos.js
index.html
package.json
src/litegraph.d.ts
src/litegraph.js
src/nodes/base.js
src/nodes/graphics.js
src/nodes/strings.js

My first PR, let's have a try.
WebCam node filters for video mode. With my device does not work, cannot use the node without knowing the expected value of "facingMode".
This mod add a property: filterFacingMode, default false

WebCamNodeFix

---

.gitignore
editor/js/defaults.js
src/litegraph.js

Changed default value for pointerevents_method property

---

src/litegraph.js

We should avoid using undeclared variables

fix: issues #272

---

src/litegraph.js

As far as I can tell removing those lines doesn't have any issues. It solves typescripts error for e.deltaX having only getter.

Shouldn't update Event.deltaX as it is read-only property

---

.eslintrc.js
src/litegraph.js

Wanted to get feedback if this is a type of change you'd be interested in. Created a sample for the arrange() function.
Why:
- Reduces scope to required / expected of variables
This change addresses the need by:
- Using let / const instead of global / var
- Update ESlint configurtation

Proposed variable type update

---

.gitignore
jest.config.js
package.json
src/litegraph.js
src/litegraph.test.js

Why:
- Every journey starts with a first step
This change addresses the need by:
- Adding jest and a test
- Resolve ESLint warnings/errors in the tested function
- Replace deprecated function
- Use let/const variable types

Add initial unit test

---

editor/js/code.js

Added scaling if editor used on high PPI screens, no changes otherwise.

Scale canvas on HiPPI screens

---

.eslintrc.js
.gitignore
package-lock.json
package.json
src/litegraph.js
src/litegraph.test.js

Why:
- Ensure that the function works as expected
This change addresses the need by:
- Add tests
- Remove duplicate logic

Add tests for registerNodeType

---

src/nodes/logic.js

https://github.com/jagenjo/litegraph.js/issues/363

missing var

---

src/litegraph.js

if the number input is something like 2+(3*2)
instead of writing Nan
it will be solved 
8 will be written

try solve the numbers equations

---

src/litegraph.js

Just adding a ctrl + shift + v short cut for pasting with the unselected nodes connected so it's easier to do mass copy paste.

Add Ctrl+Shift+V to paste with unselected nodes connected

---

src/nodes/logic.js

missing var inX

---

package.json
src/litegraph.d.ts
src/litegraph.js
src/nodes/events.js
src/nodes/gltextures.js
src/nodes/graphics.js
src/nodes/interface.js
src/nodes/math.js
src/nodes/math3d.js
src/nodes/midi.js
utils/builder.py
utils/generate_doc.sh

* Remove extending the Math & CanvasRenderingContext2D classes. It was messing up the typescript 4.9+
* Use utility classes instead of that extended functionality
* Add some type corrections in litegraph.d.ts
* Fix a couple of build issues
Closes #397

Remove extending the Javascript builtin objects

---

src/litegraph.js

Fix LGraphGroup node serialize error

---

README.md

I think Comfy UI is a prominent project using litegraph and should be added to the list of projects using litegraph.js
The link to the screenshot is a github permalink to the image from the comfyUI repo.

add comfyUI to README paragraph "projects using it"
