jagenjo/litegraph.js

src/litegraph.js

The background image works well, if you load the editor locally. But downloading from the server, background image is not always have time to load and be processed by the script. This fix corrects it.

background image fix

---

src/litegraph.js

Hey, 
I discovered that the litegraph engine showed strange behaviors in the following scenario:
Adding a new node to a graph that was loaded from file caused the links between some nodes to rearrange.
I found out that the last_node_id value was not updated when a graph was loaded from file. So the manually added node had the id 0 which already existed in the graph.
My fix tries to solve this issue. Hope this helps.
Cheers

fixing problem when adding nodes to existing graph that was loaded from file

---

src/litegraph.js

otherwise contextmenu closes before user can select an item (probably has to do with touch(pad))

contextmenu fix for chromebook

---

src/litegraph.js

Before this change, `last_link_id` is used as `next_link_id`
Cause ui issue when i use links length as `last_link_id`.

Correct use of last_link_id

---

src/nodes/base.js

Resolve Unable to use SubGraph node with webpack.
* Error message
``` "ReferenceError: 'LGraph' is not defined at Subgraph ```

Resolve "'LGraph' is not defined" issue

---

src/litegraph.js

When same node registered twice. It gives error.
ex:
LiteGraph.registerNodeType("basic/test", MyAddNode);
LiteGraph.registerNodeType("basic/test", MyAddNode);
To redefine an object property with "Object.defineProperty" method, configurable property should be set on true ( default is false)
ex : Object.defineProperty( '...' , '...' , {configurable: true})

resolve "TypeError: Cannot redefine property: shape" issue

---

src/litegraph.js

Some method names didn't match the actual method names, rendering the automatically generated documentation misleading

Documentation mismatch

---

src/nodes/network.js

Hello, love the library :)
I was trying to use the websocket node and hitting some problems:
- `this` was used instead of `that`, so the room name could never be properly checked
- JSON string was being parsed, but then when attempting to actually read attributes from it, the original raw data was used instead
With these two patches, I am able to use the websocket node as I expect.
Apologies if I have something wrong here!

Websocket node bugfixes

---

src/litegraph.d.ts

Updated onConnectInput to match current function definition
Added missing definitions for
LGraphCanvas.onDrawLinkTooltip
LGraphCanvas.onNodeMoved
LGraphCanvas.onSelectionChange
LGraphCanvas.onNodeSelected
LGraphCanvas.onNodeDeselected
LGraphCanvas.onShowNodePanel
LGraphCanvas.onNodeDblClicked
LGraphNode.onConnectionsChange
Can close #127

Update for missing type definitions

---

build/litegraph.js
build/litegraph.min.js
src/litegraph.d.ts

@jagenjo, would you like to have built files pushed on every change request?
Also, what kind of project/example graphs should I use to do smoke testing of lib stability?

Added typings for slot shape and replaced built files

---

src/litegraph.js

Hi @jagenjo. I think I found an error, basically, even if a node wasn't resizable if you clicked the "Resize" button in the Context Menu, it was going to resize it, this is so bothering especially when you've set a different node.size. I hope this is useful

Bug fixing

---

src/litegraph.js

**Purpose of change**
In a project I'm working on, I've been removing node types that aren't required by the project, but when doing this, it resulted in some unexpected sorting issues once the `registered_node_types` object begins to have items removed from it.
To get around this, I added sorting to ensure the node types / categories are always displayed in order to maintain consistency when node types are added or removed regardless of the order in `registered_node_types`
**How to use new feature**
To enable this functionality, a user needs to set `LiteGraph.auto_sort_node_types` to true, and then all subsequent context menus that are opened will have a sorted menu.
By default, the newly added property will be `false` (meaning the feature will be disabled by default) to ensure the …

Add ability to automatically sort node types / categories in the context menu

---

build/litegraph.js
build/litegraph.min.js
src/litegraph.js

The changes in this PR allow users to specify a descriptor for the properties so the property name can be displayed in a more human readable format (as per discussion on PR #178)
To specify a custom display name for a property in the context menu / editor dialog, user's can specify the descriptor info like so:
```javascript
MyNode['@propertyName'] = { descriptor: 'A More Readable Name' };
```

Add option to stylise property names

---

build/litegraph.js
build/litegraph.min.js
src/litegraph.js

This changes the descriptor terminology to `labels` as per suggestion in PR #179 
I've also included the fix to the serialisation of string properties as we spoke about in PR #178 
I've done some testing of the bug fix to make sure it doesn't break things like editing arrays, and I was able to both successfully edit arrays, and also edit strings without the serialisation issue:
Again, if this is OK, would you mind adding the `hacktoberfest-accepted` label to the pull request on GitHub so this can count to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)? Thanks :smiley:

Change property descriptor terminology + bug fix

---

src/litegraph.js

* **Resolved Issue:** If you collapse a node with a widget after loading the graph, it cannot be expanded.
* **Resolved Issue:** Compute Collapsed Nodes boundary is incorrect

Fix Boundary and collapsed issue

---

src/litegraph.js

Previously, when dragging a link from a slot with an arrow shape, the highlight was still circular. Now it just colors the arrow you drag from or to

Highlight arrow shape when connecting slots with arrow shape

---

src/litegraph.js

The seperator between node title and node body does not need to be rendered when the node title is not rendered. Otherwise, you have a floating line above your node

Separator only drawn when title is drawn

---

src/nodes/math3d.js

Adds validation to only show warning message if debug is enabled.

Fix to only show console warn if debug is enabled

---

src/litegraph.js

Found a cleaner solution: There was a property NO_TITLE already existing, but no functionality was given to it yet

Add functionality for title mode NO_TITLE

---

editor/style.css
src/litegraph.js

Touch device compatibility
- drag canvas, operate on nodes, widgets, slots
- right click simulation when second pointer is down
added LiteGraph.pointerevents_method variable ("pointer" | "mouse"), default "pointer"
replaced (Add/Remove)EventListeners with helper Litegraph.pointerListener(Add/Remove)
checks for e.isPrimary to discriminate one or more fingers down
TODO: finish checks and clean
_will remove console.log("pointerevents..) calls en integration concluded_
_multitouch gestures will be implemented on a successive tranche (pan, pinch, swipe ..)_

Touch events - alpha version

---

CONTRIBUTING.md
guides/README.md
src/nodes/midi.js

There are small typos in:
- CONTRIBUTING.md
- guides/README.md
- src/nodes/midi.js
Fixes:
- Should read `syntax` rather than `sintax`.
- Should read `outputs` rather than `otputs`.
- Should read `dragging` rather than `draging`.
- Should read `build` rather than `bulid`.
- Should read `assume` rather than `asume`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

src/litegraph.js

Custom Y-position of widgets was not updated for the widget background, only for the text inside the widget. Fixed it by taking the custom y value instead of the yPos passed to the function

make y pos of widgets customizable

---

src/litegraph.d.ts
src/litegraph.js

Hi  @jagenjo ,
We have requirement to layout network graph vertically instead horizontally  as `arrange` method of `litegraph` does ,so 
In this PR i updated `arrange` method of `litegraph` to layout nodes vertically.
Usages -
const graph = new LGraph()
1. For Horizontal Layout use as before **graph.arrange()**
2. For vertical layout use  **graph.arrange(margin,LiteGraph.VERTICAL_LAYOUT);**

Updated arrange method to support vertical layout of nodes

---

src/litegraph.d.ts

The typescript definition for LGraphNode is missing the `setProperty` method that is already implemented in the library. This PR resolves it

Add setProperty to typescript definition

---

src/nodes/base.js

Hi,
this changes the description of NodeScript nodes to contain the correct number of allowed characters.
The node description and logic did not match before.
-ClaasJG

Fix NodeScript description

---

src/litegraph.d.ts
src/litegraph.js

The feature is helpful, especially for touch devices where it would be hard to hold the Shift/Ctrl keys while selecting blocks. Only put a button on your app that turns on the multi-select mode, and there is no need to press any other keys while selecting blocks.

Add the ability to select multi nodes/blocks without pressing extra keys (shift/Ctrl)

---

src/litegraph.js

An exception was triggered when dblclicking on a node, as the variable panel was not defined. This should fix it.

Fix panel not defined.

---

src/litegraph.js

I have added checks that prevent the slider widget from drawing outside its designated area if the value is for any reason outside the expected range. I also added the ability for the program to change the colour of the slider, and the option to make the slider read only as I am using the slider to indicate audio signal volume on widgets that deal with audio signals.

Little updates to the slider widget

---

src/litegraph.js

Make that inner_value_change function will be the one to check if widget is number and parse the data to number then 
this allows others to have a chance to intercept the input coming from the prompt and do something on it 
as currently, there is no way to know the widget type and do something on the input based on that , 
so I did these changes to make that possible 
Kindly accept my pull request , and also kindly allow me to express my gratitude for your great tool 
Thanks.

organize reciving input  from prompt dialog

---

src/litegraph.js

I use a different layout on my keyboard than the physical one and e.code returns the physical key and not the remapped key.

Fix CTRL-C, CTRL-V not working on remapped keyboards.

---

src/litegraph.js

Extends the regex to allow number[dot]number in the evaluation, e.g. `(8.25 * 3.25) / 2.5 + 1.275` is now supported
I've added `\d\.\d` explicitly rather than just adding it to the range as it seemed safer.

Add support for decimal evaluation

---

src/litegraph.js

This unifies the change handling between _slider_ and _number_ widgets and makes it possible to have a property value automatically reflect the widget.

Fix: inner_value_change not called on slider interaction

---

guides/README.md
src/litegraph.js

Gives the ability for node to override the global graph canvas `allow_interaction` on a per node basis. Also allow to drag a nodes when `allow_interaction` is `false` on the graph canvas settings.
Having a sample graph for users to view with partial interaction enabled on specific nodes. In out case the first node in the graph in an input node with some pre-defined sample images.
We wanted the user to be able to trigger widget actions but also be allowed to drag all nodes around as a kind of semi-interacted preview of what can be done.
- used the existing `drag_node` graph cavas setting to allow dragging when interactions are off
- overriding interactions on a node only enables the interaction with the content of the node not any of the links

Allow interactions per node override

---

guides/README.md

We needed integer precision number widgets, and noticed the feature was already there in the code. This updates the guide to mention the `precision` widget option that can be used for number widgets.

Update documentation to mention 'precision' as widget option

---

guides/README.md
src/litegraph.js

The previous PR #385 was using an extra `drag_mode` flag to accomplish per node interaction override. 
This small tweak removes that requirement by getting access to the node earlier in the `processMouseMove()` function and checking the `allow_interaction` flag on the node (if available). This means that `drag_mode` isn't required for the condition check like the previous implementation.

Simplify the allow_interaction override to only use node flags

---

src/litegraph.js
utils/server.js

This PR adds the ability to align selected nodes in two ways:
1. Right clicking the canvas will allow aligning nodes to the furthest node in the direction that is selected
2. Right clicking a node allows aligning all selected nodes to the node that right clicked.
(Also includes a minor change to the server.js in the example to allow easier navigation to the web interface)
Assuming this is a feature that is of interest, I have a couple specific things I'm looking for feedback on:
1. Menu order/phrasing
2. Suggestions/preference around how alignment should be calculated when aligned via canvas context menu
Short Demo:

Add ability to align selected nodes

---

src/litegraph.js

This allows widgets to have a label defined in addition to a name, allowing for language/user defined widget display names but constant internal names

Render widget label in preference to name

---

src/litegraph.js
src/nodes/base.js

I would like the ability to use a globally unique ID instead of integers when dealing with nodes in subgraphs. The problem is:
- The project I contribute to ([ComfyUI](https://github.com/comfyanonymous/ComfyUI/tree/master/web)) serializes the entire graph by using the node ID as an identifier, then passes it to the backend
- The issue comes into play if subgraphs are introduced. Each subgraph has an individual last node ID counter starting from 0, so the nodes may no longer be unique if they're added into subgraphs
So I needed a way to uniquely identify nodes across all subgraphs without a central ID store, which is UUIDs in this case. This would allow subgraphs to be compatible with the project's backend graph format

Option to use UUIDs instead of integers for node IDs

---

src/litegraph.js

Fixed exports for rollup, first addressed here, but last time prettier got in the way and refactored all code.
https://github.com/jagenjo/litegraph.js/pull/353
This time I disabled it.

Fixed exports for rollup bundler

---

build/litegraph.core.js

If the node is pinned,
* Block single node dragging.
* Allow other actions.
* Allow dragging of multiple selected nodes.

block node dragging if node is 'pinned'

---

src/litegraph.js

This bug occurred when hovering over a menu that is disabled in the context menu.

Fix auto-open bug in context menu

---

src/litegraph.js

#409 
Following your answer @jagenjo , here is the PR. Thank you for your quick answer.

replacing slider precision harcoded value

---

utils/server.js

hi!
im used to clicking the url and having the browser open the page.
the '!' at the end of the url ('... http://127.0.0.1:8000!') makes it not possible to click and open the browser from terminal in vscode as usual so i propose simply removing it

refactor: remove '!' from server url

---

src/litegraph.js

Fixes issue #420
Logic that checked to see if a property was set would return 'false' when the value was zero, so any numeric widget set to 0 would not be restored correctly.

Fixes issue with restoring serialised graphs with widgets set to 0.
